// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-mitP9Gw_8tVGQZID-tk-oIvd0gPPJqY',
    appId: '1:352515485244:web:1ae29d60cc8224aebd1d39',
    messagingSenderId: '352515485244',
    projectId: 'uniride-fcc85',
    authDomain: 'uniride-fcc85.firebaseapp.com',
    storageBucket: 'uniride-fcc85.firebasestorage.app',
    measurementId: 'G-QSX9RG13FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD21V4uM60CBfFtl0RqeIQ0R4nYjKQYt_w',
    appId: '1:352515485244:android:ed42b2da47a36c8ebd1d39',
    messagingSenderId: '352515485244',
    projectId: 'uniride-fcc85',
    storageBucket: 'uniride-fcc85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMqafToF3BmXAtlHfeZcHmS5pOoqE-3Us',
    appId: '1:352515485244:ios:9539de83f7c61d16bd1d39',
    messagingSenderId: '352515485244',
    projectId: 'uniride-fcc85',
    storageBucket: 'uniride-fcc85.firebasestorage.app',
    iosBundleId: 'com.example.unirideApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMqafToF3BmXAtlHfeZcHmS5pOoqE-3Us',
    appId: '1:352515485244:ios:9539de83f7c61d16bd1d39',
    messagingSenderId: '352515485244',
    projectId: 'uniride-fcc85',
    storageBucket: 'uniride-fcc85.firebasestorage.app',
    iosBundleId: 'com.example.unirideApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-mitP9Gw_8tVGQZID-tk-oIvd0gPPJqY',
    appId: '1:352515485244:web:b4de030a2d5c9040bd1d39',
    messagingSenderId: '352515485244',
    projectId: 'uniride-fcc85',
    authDomain: 'uniride-fcc85.firebaseapp.com',
    storageBucket: 'uniride-fcc85.firebasestorage.app',
    measurementId: 'G-VDXDPXW4ZQ',
  );

}